package metier;
// Generated 2020-2-8 10:16:55 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Affecter generated by hbm2java
 */
public class Affecter  implements java.io.Serializable {


     private AffecterId id;
     private Client client;
     private Programme programme;
     private Date datefin;
     private String statut;

    public Affecter() {
    }

	
    public Affecter(AffecterId id, Client client, Programme programme) {
        this.id = id;
        this.client = client;
        this.programme = programme;
    }
    public Affecter(AffecterId id, Client client, Programme programme, Date datefin, String statut) {
       this.id = id;
       this.client = client;
       this.programme = programme;
       this.datefin = datefin;
       this.statut = statut;
    }
   
    public AffecterId getId() {
        return this.id;
    }
    
    public void setId(AffecterId id) {
        this.id = id;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Programme getProgramme() {
        return this.programme;
    }
    
    public void setProgramme(Programme programme) {
        this.programme = programme;
    }
    public Date getDatefin() {
        return this.datefin;
    }
    
    public void setDatefin(Date datefin) {
        this.datefin = datefin;
    }
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }




}


