package metier;
// Generated 2020-2-8 10:16:55 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AffecterId generated by hbm2java
 */
public class AffecterId  implements java.io.Serializable {


     private int codep;
     private int codec;
     private Date dateaffectation;

    public AffecterId() {
    }

    public AffecterId(int codep, int codec, Date dateaffectation) {
       this.codep = codep;
       this.codec = codec;
       this.dateaffectation = dateaffectation;
    }
   
    public int getCodep() {
        return this.codep;
    }
    
    public void setCodep(int codep) {
        this.codep = codep;
    }
    public int getCodec() {
        return this.codec;
    }
    
    public void setCodec(int codec) {
        this.codec = codec;
    }
    public Date getDateaffectation() {
        return this.dateaffectation;
    }
    
    public void setDateaffectation(Date dateaffectation) {
        this.dateaffectation = dateaffectation;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AffecterId) ) return false;
		 AffecterId castOther = ( AffecterId ) other; 
         
		 return (this.getCodep()==castOther.getCodep())
 && (this.getCodec()==castOther.getCodec())
 && ( (this.getDateaffectation()==castOther.getDateaffectation()) || ( this.getDateaffectation()!=null && castOther.getDateaffectation()!=null && this.getDateaffectation().equals(castOther.getDateaffectation()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodep();
         result = 37 * result + this.getCodec();
         result = 37 * result + ( getDateaffectation() == null ? 0 : this.getDateaffectation().hashCode() );
         return result;
   }   


}


