package metier;
// Generated 2020-2-8 11:12:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Circuit generated by hbm2java
 */
public class Circuit  implements java.io.Serializable {


     private Integer codecir;
     private String nomcir;
     private Set seances = new HashSet(0);
     private Set executerCircuits = new HashSet(0);
     private Set decomposerExos = new HashSet(0);

    public Circuit() {
    }

    public Circuit(String nomcir, Set seances, Set executerCircuits, Set decomposerExos) {
       this.nomcir = nomcir;
       this.seances = seances;
       this.executerCircuits = executerCircuits;
       this.decomposerExos = decomposerExos;
    }
   
    public Integer getCodecir() {
        return this.codecir;
    }
    
    public void setCodecir(Integer codecir) {
        this.codecir = codecir;
    }
    public String getNomcir() {
        return this.nomcir;
    }
    
    public void setNomcir(String nomcir) {
        this.nomcir = nomcir;
    }
    public Set getSeances() {
        return this.seances;
    }
    
    public void setSeances(Set seances) {
        this.seances = seances;
    }
    public Set getExecuterCircuits() {
        return this.executerCircuits;
    }
    
    public void setExecuterCircuits(Set executerCircuits) {
        this.executerCircuits = executerCircuits;
    }
    public Set getDecomposerExos() {
        return this.decomposerExos;
    }
    
    public void setDecomposerExos(Set decomposerExos) {
        this.decomposerExos = decomposerExos;
    }




}


