package metier;
// Generated 2020-2-8 10:16:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer codec;
     private Profil profil;
     private User user;
     private String nomc;
     private String prenomc;
     private Date datenaissc;
     private String taillec;
     private String poidsc;
     private String mailc;
     private String telc;
     private Date dateinscriptionc;
     private String commentaireadminc;
     private String statutc;
     private String sexec;
     private Set executerCircuits = new HashSet(0);
     private Set affecters = new HashSet(0);
     private Set evaluers = new HashSet(0);
     private Set executerexos = new HashSet(0);

    public Client() {
    }

    public Client(Profil profil, User user, String nomc, String prenomc, Date datenaissc, String taillec, String poidsc, String mailc, String telc, Date dateinscriptionc, String commentaireadminc, String statutc, String sexec, Set executerCircuits, Set affecters, Set evaluers, Set executerexos) {
       this.profil = profil;
       this.user = user;
       this.nomc = nomc;
       this.prenomc = prenomc;
       this.datenaissc = datenaissc;
       this.taillec = taillec;
       this.poidsc = poidsc;
       this.mailc = mailc;
       this.telc = telc;
       this.dateinscriptionc = dateinscriptionc;
       this.commentaireadminc = commentaireadminc;
       this.statutc = statutc;
       this.sexec = sexec;
       this.executerCircuits = executerCircuits;
       this.affecters = affecters;
       this.evaluers = evaluers;
       this.executerexos = executerexos;
    }
   
    public Integer getCodec() {
        return this.codec;
    }
    
    public void setCodec(Integer codec) {
        this.codec = codec;
    }
    public Profil getProfil() {
        return this.profil;
    }
    
    public void setProfil(Profil profil) {
        this.profil = profil;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getNomc() {
        return this.nomc;
    }
    
    public void setNomc(String nomc) {
        this.nomc = nomc;
    }
    public String getPrenomc() {
        return this.prenomc;
    }
    
    public void setPrenomc(String prenomc) {
        this.prenomc = prenomc;
    }
    public Date getDatenaissc() {
        return this.datenaissc;
    }
    
    public void setDatenaissc(Date datenaissc) {
        this.datenaissc = datenaissc;
    }
    public String getTaillec() {
        return this.taillec;
    }
    
    public void setTaillec(String taillec) {
        this.taillec = taillec;
    }
    public String getPoidsc() {
        return this.poidsc;
    }
    
    public void setPoidsc(String poidsc) {
        this.poidsc = poidsc;
    }
    public String getMailc() {
        return this.mailc;
    }
    
    public void setMailc(String mailc) {
        this.mailc = mailc;
    }
    public String getTelc() {
        return this.telc;
    }
    
    public void setTelc(String telc) {
        this.telc = telc;
    }
    public Date getDateinscriptionc() {
        return this.dateinscriptionc;
    }
    
    public void setDateinscriptionc(Date dateinscriptionc) {
        this.dateinscriptionc = dateinscriptionc;
    }
    public String getCommentaireadminc() {
        return this.commentaireadminc;
    }
    
    public void setCommentaireadminc(String commentaireadminc) {
        this.commentaireadminc = commentaireadminc;
    }
    public String getStatutc() {
        return this.statutc;
    }
    
    public void setStatutc(String statutc) {
        this.statutc = statutc;
    }
    public String getSexec() {
        return this.sexec;
    }
    
    public void setSexec(String sexec) {
        this.sexec = sexec;
    }
    public Set getExecuterCircuits() {
        return this.executerCircuits;
    }
    
    public void setExecuterCircuits(Set executerCircuits) {
        this.executerCircuits = executerCircuits;
    }
    public Set getAffecters() {
        return this.affecters;
    }
    
    public void setAffecters(Set affecters) {
        this.affecters = affecters;
    }
    public Set getEvaluers() {
        return this.evaluers;
    }
    
    public void setEvaluers(Set evaluers) {
        this.evaluers = evaluers;
    }
    public Set getExecuterexos() {
        return this.executerexos;
    }
    
    public void setExecuterexos(Set executerexos) {
        this.executerexos = executerexos;
    }




}


