package metier;
// Generated 2020-2-8 10:16:55 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Coach generated by hbm2java
 */
public class Coach  implements java.io.Serializable {


     private int idcoach;
     private User user;
     private String nomcoach;
     private String prenomcoach;
     private Date datenaisscoach;
     private String sexecoach;

    public Coach() {
    }

	
    public Coach(int idcoach) {
        this.idcoach = idcoach;
    }
    public Coach(int idcoach, User user, String nomcoach, String prenomcoach, Date datenaisscoach, String sexecoach) {
       this.idcoach = idcoach;
       this.user = user;
       this.nomcoach = nomcoach;
       this.prenomcoach = prenomcoach;
       this.datenaisscoach = datenaisscoach;
       this.sexecoach = sexecoach;
    }
   
    public int getIdcoach() {
        return this.idcoach;
    }
    
    public void setIdcoach(int idcoach) {
        this.idcoach = idcoach;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getNomcoach() {
        return this.nomcoach;
    }
    
    public void setNomcoach(String nomcoach) {
        this.nomcoach = nomcoach;
    }
    public String getPrenomcoach() {
        return this.prenomcoach;
    }
    
    public void setPrenomcoach(String prenomcoach) {
        this.prenomcoach = prenomcoach;
    }
    public Date getDatenaisscoach() {
        return this.datenaisscoach;
    }
    
    public void setDatenaisscoach(Date datenaisscoach) {
        this.datenaisscoach = datenaisscoach;
    }
    public String getSexecoach() {
        return this.sexecoach;
    }
    
    public void setSexecoach(String sexecoach) {
        this.sexecoach = sexecoach;
    }




}


