package metier;
// Generated 2020-2-8 10:16:55 by Hibernate Tools 4.3.1



/**
 * ComprendreExercice generated by hbm2java
 */
public class ComprendreExercice  implements java.io.Serializable {


     private ComprendreExerciceId id;
     private Exercice exercice;
     private Seance seance;
     private Integer ordreexo;

    public ComprendreExercice() {
    }

	
    public ComprendreExercice(ComprendreExerciceId id, Exercice exercice, Seance seance) {
        this.id = id;
        this.exercice = exercice;
        this.seance = seance;
    }
    public ComprendreExercice(ComprendreExerciceId id, Exercice exercice, Seance seance, Integer ordreexo) {
       this.id = id;
       this.exercice = exercice;
       this.seance = seance;
       this.ordreexo = ordreexo;
    }
   
    public ComprendreExerciceId getId() {
        return this.id;
    }
    
    public void setId(ComprendreExerciceId id) {
        this.id = id;
    }
    public Exercice getExercice() {
        return this.exercice;
    }
    
    public void setExercice(Exercice exercice) {
        this.exercice = exercice;
    }
    public Seance getSeance() {
        return this.seance;
    }
    
    public void setSeance(Seance seance) {
        this.seance = seance;
    }
    public Integer getOrdreexo() {
        return this.ordreexo;
    }
    
    public void setOrdreexo(Integer ordreexo) {
        this.ordreexo = ordreexo;
    }




}


