package metier;
// Generated 2020-2-8 11:12:39 by Hibernate Tools 4.3.1



/**
 * DecomposerExoId generated by hbm2java
 */
public class DecomposerExoId  implements java.io.Serializable {


     private int codee;
     private int codecir;

    public DecomposerExoId() {
    }

    public DecomposerExoId(int codee, int codecir) {
       this.codee = codee;
       this.codecir = codecir;
    }
   
    public int getCodee() {
        return this.codee;
    }
    
    public void setCodee(int codee) {
        this.codee = codee;
    }
    public int getCodecir() {
        return this.codecir;
    }
    
    public void setCodecir(int codecir) {
        this.codecir = codecir;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DecomposerExoId) ) return false;
		 DecomposerExoId castOther = ( DecomposerExoId ) other; 
         
		 return (this.getCodee()==castOther.getCodee())
 && (this.getCodecir()==castOther.getCodecir());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodee();
         result = 37 * result + this.getCodecir();
         return result;
   }   


}


