package metier;
// Generated 2020-2-8 10:16:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Difficulte generated by hbm2java
 */
public class Difficulte  implements java.io.Serializable {


     private int coded;
     private String nomd;
     private Set executerexos = new HashSet(0);

    public Difficulte() {
    }

	
    public Difficulte(int coded) {
        this.coded = coded;
    }
    public Difficulte(int coded, String nomd, Set executerexos) {
       this.coded = coded;
       this.nomd = nomd;
       this.executerexos = executerexos;
    }
   
    public int getCoded() {
        return this.coded;
    }
    
    public void setCoded(int coded) {
        this.coded = coded;
    }
    public String getNomd() {
        return this.nomd;
    }
    
    public void setNomd(String nomd) {
        this.nomd = nomd;
    }
    public Set getExecuterexos() {
        return this.executerexos;
    }
    
    public void setExecuterexos(Set executerexos) {
        this.executerexos = executerexos;
    }




}


