package metier;
// Generated 2020-2-8 11:12:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Difficulte generated by hbm2java
 */
public class Difficulte  implements java.io.Serializable {


     private Integer coded;
     private String nomd;
     private Set executerexos = new HashSet(0);

    public Difficulte() {
    }

    public Difficulte(String nomd, Set executerexos) {
       this.nomd = nomd;
       this.executerexos = executerexos;
    }
   
    public Integer getCoded() {
        return this.coded;
    }
    
    public void setCoded(Integer coded) {
        this.coded = coded;
    }
    public String getNomd() {
        return this.nomd;
    }
    
    public void setNomd(String nomd) {
        this.nomd = nomd;
    }
    public Set getExecuterexos() {
        return this.executerexos;
    }
    
    public void setExecuterexos(Set executerexos) {
        this.executerexos = executerexos;
    }




}


