package metier;
// Generated 2020-2-8 11:12:39 by Hibernate Tools 4.3.1



/**
 * Evaluer generated by hbm2java
 */
public class Evaluer  implements java.io.Serializable {


     private EvaluerId id;
     private Client client;
     private Seance seance;
     private String bras;
     private String poitrine;
     private String taille;
     private String hanches;
     private String cuisses;
     private Double cinqMinallong;
     private Double apresflexion;
     private Double uneMinallong;

    public Evaluer() {
    }

	
    public Evaluer(EvaluerId id, Client client, Seance seance) {
        this.id = id;
        this.client = client;
        this.seance = seance;
    }
    public Evaluer(EvaluerId id, Client client, Seance seance, String bras, String poitrine, String taille, String hanches, String cuisses, Double cinqMinallong, Double apresflexion, Double uneMinallong) {
       this.id = id;
       this.client = client;
       this.seance = seance;
       this.bras = bras;
       this.poitrine = poitrine;
       this.taille = taille;
       this.hanches = hanches;
       this.cuisses = cuisses;
       this.cinqMinallong = cinqMinallong;
       this.apresflexion = apresflexion;
       this.uneMinallong = uneMinallong;
    }
   
    public EvaluerId getId() {
        return this.id;
    }
    
    public void setId(EvaluerId id) {
        this.id = id;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Seance getSeance() {
        return this.seance;
    }
    
    public void setSeance(Seance seance) {
        this.seance = seance;
    }
    public String getBras() {
        return this.bras;
    }
    
    public void setBras(String bras) {
        this.bras = bras;
    }
    public String getPoitrine() {
        return this.poitrine;
    }
    
    public void setPoitrine(String poitrine) {
        this.poitrine = poitrine;
    }
    public String getTaille() {
        return this.taille;
    }
    
    public void setTaille(String taille) {
        this.taille = taille;
    }
    public String getHanches() {
        return this.hanches;
    }
    
    public void setHanches(String hanches) {
        this.hanches = hanches;
    }
    public String getCuisses() {
        return this.cuisses;
    }
    
    public void setCuisses(String cuisses) {
        this.cuisses = cuisses;
    }
    public Double getcinqMinallong() {
        return this.cinqMinallong;
    }
    
    public void setcinqMinallong(Double cinqMinallong) {
        this.cinqMinallong = cinqMinallong;
    }
    public Double getApresflexion() {
        return this.apresflexion;
    }
    
    public void setApresflexion(Double apresflexion) {
        this.apresflexion = apresflexion;
    }
    public Double getuneMinallong() {
        return this.uneMinallong;
    }
    
    public void setuneMinallong(Double uneMinallong) {
        this.uneMinallong = uneMinallong;
    }




}


