package metier;
// Generated 2020-2-8 10:16:55 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EvaluerId generated by hbm2java
 */
public class EvaluerId  implements java.io.Serializable {


     private int codes;
     private int codec;
     private Date dateeval;

    public EvaluerId() {
    }

    public EvaluerId(int codes, int codec, Date dateeval) {
       this.codes = codes;
       this.codec = codec;
       this.dateeval = dateeval;
    }
   
    public int getCodes() {
        return this.codes;
    }
    
    public void setCodes(int codes) {
        this.codes = codes;
    }
    public int getCodec() {
        return this.codec;
    }
    
    public void setCodec(int codec) {
        this.codec = codec;
    }
    public Date getDateeval() {
        return this.dateeval;
    }
    
    public void setDateeval(Date dateeval) {
        this.dateeval = dateeval;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EvaluerId) ) return false;
		 EvaluerId castOther = ( EvaluerId ) other; 
         
		 return (this.getCodes()==castOther.getCodes())
 && (this.getCodec()==castOther.getCodec())
 && ( (this.getDateeval()==castOther.getDateeval()) || ( this.getDateeval()!=null && castOther.getDateeval()!=null && this.getDateeval().equals(castOther.getDateeval()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodes();
         result = 37 * result + this.getCodec();
         result = 37 * result + ( getDateeval() == null ? 0 : this.getDateeval().hashCode() );
         return result;
   }   


}


