package metier;
// Generated 2020-2-8 11:12:39 by Hibernate Tools 4.3.1



/**
 * ExecuterCircuitId generated by hbm2java
 */
public class ExecuterCircuitId  implements java.io.Serializable {


     private int codeos;
     private int codecir;
     private int codec;

    public ExecuterCircuitId() {
    }

    public ExecuterCircuitId(int codeos, int codecir, int codec) {
       this.codeos = codeos;
       this.codecir = codecir;
       this.codec = codec;
    }
   
    public int getCodeos() {
        return this.codeos;
    }
    
    public void setCodeos(int codeos) {
        this.codeos = codeos;
    }
    public int getCodecir() {
        return this.codecir;
    }
    
    public void setCodecir(int codecir) {
        this.codecir = codecir;
    }
    public int getCodec() {
        return this.codec;
    }
    
    public void setCodec(int codec) {
        this.codec = codec;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ExecuterCircuitId) ) return false;
		 ExecuterCircuitId castOther = ( ExecuterCircuitId ) other; 
         
		 return (this.getCodeos()==castOther.getCodeos())
 && (this.getCodecir()==castOther.getCodecir())
 && (this.getCodec()==castOther.getCodec());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodeos();
         result = 37 * result + this.getCodecir();
         result = 37 * result + this.getCodec();
         return result;
   }   


}


