package metier;
// Generated 2020-2-8 11:12:39 by Hibernate Tools 4.3.1



/**
 * ExecuterCircuit generated by hbm2java
 */
public class ExecuterCircuit  implements java.io.Serializable {


     private ExecuterCircuitId id;
     private Circuit circuit;
     private Client client;
     private Occurences occurences;
     private Double min;
     private Double max;
     private Double recup;

    public ExecuterCircuit() {
    }

	
    public ExecuterCircuit(ExecuterCircuitId id, Circuit circuit, Client client, Occurences occurences) {
        this.id = id;
        this.circuit = circuit;
        this.client = client;
        this.occurences = occurences;
    }
    public ExecuterCircuit(ExecuterCircuitId id, Circuit circuit, Client client, Occurences occurences, Double min, Double max, Double recup) {
       this.id = id;
       this.circuit = circuit;
       this.client = client;
       this.occurences = occurences;
       this.min = min;
       this.max = max;
       this.recup = recup;
    }
   
    public ExecuterCircuitId getId() {
        return this.id;
    }
    
    public void setId(ExecuterCircuitId id) {
        this.id = id;
    }
    public Circuit getCircuit() {
        return this.circuit;
    }
    
    public void setCircuit(Circuit circuit) {
        this.circuit = circuit;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Occurences getOccurences() {
        return this.occurences;
    }
    
    public void setOccurences(Occurences occurences) {
        this.occurences = occurences;
    }
    public Double getMin() {
        return this.min;
    }
    
    public void setMin(Double min) {
        this.min = min;
    }
    public Double getMax() {
        return this.max;
    }
    
    public void setMax(Double max) {
        this.max = max;
    }
    public Double getRecup() {
        return this.recup;
    }
    
    public void setRecup(Double recup) {
        this.recup = recup;
    }




}


