package metier;
// Generated 2020-2-8 11:12:39 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Occurences generated by hbm2java
 */
public class Occurences  implements java.io.Serializable {


     private Integer codeos;
     private Seance seance;
     private Date dateos;
     private Boolean isvalid;
     private Set executerCircuits = new HashSet(0);
     private Set executerexos = new HashSet(0);

    public Occurences() {
    }

	
    public Occurences(Seance seance) {
        this.seance = seance;
    }
    public Occurences(Seance seance, Date dateos, Boolean isvalid, Set executerCircuits, Set executerexos) {
       this.seance = seance;
       this.dateos = dateos;
       this.isvalid = isvalid;
       this.executerCircuits = executerCircuits;
       this.executerexos = executerexos;
    }
   
    public Integer getCodeos() {
        return this.codeos;
    }
    
    public void setCodeos(Integer codeos) {
        this.codeos = codeos;
    }
    public Seance getSeance() {
        return this.seance;
    }
    
    public void setSeance(Seance seance) {
        this.seance = seance;
    }
    public Date getDateos() {
        return this.dateos;
    }
    
    public void setDateos(Date dateos) {
        this.dateos = dateos;
    }
    public Boolean getIsvalid() {
        return this.isvalid;
    }
    
    public void setIsvalid(Boolean isvalid) {
        this.isvalid = isvalid;
    }
    public Set getExecuterCircuits() {
        return this.executerCircuits;
    }
    
    public void setExecuterCircuits(Set executerCircuits) {
        this.executerCircuits = executerCircuits;
    }
    public Set getExecuterexos() {
        return this.executerexos;
    }
    
    public void setExecuterexos(Set executerexos) {
        this.executerexos = executerexos;
    }




}


