package metier;
// Generated 2020-2-8 10:16:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Occurences generated by hbm2java
 */
public class Occurences  implements java.io.Serializable {


     private int codeos;
     private Seance seance;
     private Date dateos;
     private Set executerCircuits = new HashSet(0);
     private Set executerexos = new HashSet(0);

    public Occurences() {
    }

	
    public Occurences(int codeos, Seance seance) {
        this.codeos = codeos;
        this.seance = seance;
    }
    public Occurences(int codeos, Seance seance, Date dateos, Set executerCircuits, Set executerexos) {
       this.codeos = codeos;
       this.seance = seance;
       this.dateos = dateos;
       this.executerCircuits = executerCircuits;
       this.executerexos = executerexos;
    }
   
    public int getCodeos() {
        return this.codeos;
    }
    
    public void setCodeos(int codeos) {
        this.codeos = codeos;
    }
    public Seance getSeance() {
        return this.seance;
    }
    
    public void setSeance(Seance seance) {
        this.seance = seance;
    }
    public Date getDateos() {
        return this.dateos;
    }
    
    public void setDateos(Date dateos) {
        this.dateos = dateos;
    }
    public Set getExecuterCircuits() {
        return this.executerCircuits;
    }
    
    public void setExecuterCircuits(Set executerCircuits) {
        this.executerCircuits = executerCircuits;
    }
    public Set getExecuterexos() {
        return this.executerexos;
    }
    
    public void setExecuterexos(Set executerexos) {
        this.executerexos = executerexos;
    }




}


