package metier;
// Generated 2020-2-8 10:16:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profil generated by hbm2java
 */
public class Profil  implements java.io.Serializable {


     private int codepro;
     private String nompro;
     private Set programmes = new HashSet(0);
     private Set clients = new HashSet(0);

    public Profil() {
    }

	
    public Profil(int codepro) {
        this.codepro = codepro;
    }
    public Profil(int codepro, String nompro, Set programmes, Set clients) {
       this.codepro = codepro;
       this.nompro = nompro;
       this.programmes = programmes;
       this.clients = clients;
    }
   
    public int getCodepro() {
        return this.codepro;
    }
    
    public void setCodepro(int codepro) {
        this.codepro = codepro;
    }
    public String getNompro() {
        return this.nompro;
    }
    
    public void setNompro(String nompro) {
        this.nompro = nompro;
    }
    public Set getProgrammes() {
        return this.programmes;
    }
    
    public void setProgrammes(Set programmes) {
        this.programmes = programmes;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }




}


