package metier;
// Generated 2020-2-8 11:12:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profil generated by hbm2java
 */
public class Profil  implements java.io.Serializable {


     private Integer codepro;
     private String nompro;
     private Set programmes = new HashSet(0);
     private Set clients = new HashSet(0);

    public Profil() {
    }

    public Profil(String nompro, Set programmes, Set clients) {
       this.nompro = nompro;
       this.programmes = programmes;
       this.clients = clients;
    }
   
    public Integer getCodepro() {
        return this.codepro;
    }
    
    public void setCodepro(Integer codepro) {
        this.codepro = codepro;
    }
    public String getNompro() {
        return this.nompro;
    }
    
    public void setNompro(String nompro) {
        this.nompro = nompro;
    }
    public Set getProgrammes() {
        return this.programmes;
    }
    
    public void setProgrammes(Set programmes) {
        this.programmes = programmes;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }




}


