package metier;
// Generated 2020-2-8 10:16:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Seance generated by hbm2java
 */
public class Seance  implements java.io.Serializable {


     private int codes;
     private Circuit circuit;
     private String noms;
     private Boolean isbilan;
     private Boolean isvalide;
     private Set comprendreExercices = new HashSet(0);
     private Set evaluers = new HashSet(0);
     private Set occurenceses = new HashSet(0);
     private Set programmes = new HashSet(0);

    public Seance() {
    }

	
    public Seance(int codes) {
        this.codes = codes;
    }
    public Seance(int codes, Circuit circuit, String noms, Boolean isbilan, Boolean isvalide, Set comprendreExercices, Set evaluers, Set occurenceses, Set programmes) {
       this.codes = codes;
       this.circuit = circuit;
       this.noms = noms;
       this.isbilan = isbilan;
       this.isvalide = isvalide;
       this.comprendreExercices = comprendreExercices;
       this.evaluers = evaluers;
       this.occurenceses = occurenceses;
       this.programmes = programmes;
    }
   
    public int getCodes() {
        return this.codes;
    }
    
    public void setCodes(int codes) {
        this.codes = codes;
    }
    public Circuit getCircuit() {
        return this.circuit;
    }
    
    public void setCircuit(Circuit circuit) {
        this.circuit = circuit;
    }
    public String getNoms() {
        return this.noms;
    }
    
    public void setNoms(String noms) {
        this.noms = noms;
    }
    public Boolean getIsbilan() {
        return this.isbilan;
    }
    
    public void setIsbilan(Boolean isbilan) {
        this.isbilan = isbilan;
    }
    public Boolean getIsvalide() {
        return this.isvalide;
    }
    
    public void setIsvalide(Boolean isvalide) {
        this.isvalide = isvalide;
    }
    public Set getComprendreExercices() {
        return this.comprendreExercices;
    }
    
    public void setComprendreExercices(Set comprendreExercices) {
        this.comprendreExercices = comprendreExercices;
    }
    public Set getEvaluers() {
        return this.evaluers;
    }
    
    public void setEvaluers(Set evaluers) {
        this.evaluers = evaluers;
    }
    public Set getOccurenceses() {
        return this.occurenceses;
    }
    
    public void setOccurenceses(Set occurenceses) {
        this.occurenceses = occurenceses;
    }
    public Set getProgrammes() {
        return this.programmes;
    }
    
    public void setProgrammes(Set programmes) {
        this.programmes = programmes;
    }




}


